### ISSUE TITLE
error handling

### ISSUE THREAD

**Issue by Karyum** [WebAhead6/Tarek-autoSearch#7]
one of the goal of the project was to do error handling to pieces of code that might give you an error, or tell the user that something has went wrong with what they are trying to do.

i'll list the lines that needs error handling:
https://github.com/WebAhead6/Tarek-autoSearch/blob/master/public/index.js#L56

[missing a catch here](https://github.com/WebAhead6/Tarek-autoSearch/blob/master/public/index.js#L23-L36)

[maybe send a response here that no data was given](https://github.com/WebAhead6/Tarek-autoSearch/blob/master/handlers/cardetails.js#L29-L31)

https://github.com/WebAhead6/Tarek-autoSearch/blob/master/handlers/cardetails.js#L28

**Comment by Karyum** [comment]
why did you close the issues ? 😅

**Comment by Tarekb93** [comment]
issues has been fixed. (It think fixed correctly :smile: )


check updated project.
