### ISSUE TITLE
unused code 

### ISSUE THREAD

**Issue by Karyum** [WebAhead6/Tarek-autoSearch#8]
i'll add here some code that is not being used.

https://github.com/WebAhead6/Tarek-autoSearch/blob/master/public/index.js#L13-L15

[you don't really need an else here](https://github.com/WebAhead6/Tarek-autoSearch/blob/master/public/index.js#L43-L45)

https://github.com/WebAhead6/Tarek-autoSearch/blob/master/handlers/cardetails.js#L4

**Comment by Tarekb93** [comment]
Done
